import { Event } from "./types";

export const MOCK_EVENTS: Event[] = [
  {
    id: "1",
    title: "Sunset Jazz Festival",
    description: "Experience the soulful rhythms of the city's finest jazz ensemble under the open sky.",
    category: "Music",
    date: "2024-10-05",
    startTime: "18:00",
    endTime: "22:00",
    venue: "The Grand Plaza Courtyard",
    address: "123 Harmonic Avenue, Music District, NY 10001",
    price: 45,
    artistName: "Crescent City Quintet",
    perks: ["Premium outdoor seating", "Complimentary welcome drink", "Digital event program"],
    isSaved: true,
  },
  {
    id: "2",
    title: "Hamlet: Modern Reimagining",
    description: "A groundbreaking adaptation of Shakespeare's classic tragedy set in a corporate dystopia.",
    category: "Theater",
    date: "2024-10-05",
    startTime: "19:30",
    endTime: "21:30",
    venue: "City Playhouse",
    address: "45 Stage Lane, Arts Quarter, NY 10002",
    price: 60,
    isSaved: false,
  },
  {
    id: "3",
    title: "Gallery Night Opening",
    description: "Discover emerging local artists at the monthly gallery night. Wine and cheese included.",
    category: "Art",
    date: "2024-10-05",
    startTime: "17:00",
    endTime: "21:00",
    venue: "Downtown Art Gallery",
    address: "78 Canvas Street, Gallery Row, NY 10003",
    price: 15,
    isSaved: false,
  },
  {
    id: "4",
    title: "Jazz Night",
    description: "An intimate evening of smooth jazz in a cozy underground venue.",
    category: "Music",
    date: "2024-10-02",
    startTime: "20:00",
    endTime: "23:00",
    venue: "Blue Note Underground",
    address: "12 Jazz Alley, Midtown, NY 10004",
    price: 30,
    isSaved: false,
  },
  {
    id: "5",
    title: "Festival Gastronómico",
    description: "Taste dishes from over 40 local restaurants and food trucks in one vibrant outdoor festival.",
    category: "Food",
    date: "2024-10-05",
    startTime: "12:00",
    endTime: "20:00",
    venue: "Central Park Lawn",
    address: "Central Park West, NY 10023",
    price: 20,
    isSaved: false,
  },
  {
    id: "6",
    title: "Neon Party",
    description: "Dance the night away under neon lights with top DJs spinning the latest hits.",
    category: "Parties",
    date: "2024-10-08",
    startTime: "22:00",
    endTime: "04:00",
    venue: "Electric Club",
    address: "200 Neon Blvd, Downtown, NY 10005",
    price: 25,
    isSaved: false,
  },
  {
    id: "7",
    title: "Yoga en el Parque",
    description: "Start your morning with a guided yoga session in the park. All levels welcome.",
    category: "Wellness",
    date: "2024-10-15",
    startTime: "08:00",
    endTime: "09:30",
    venue: "Riverside Park",
    address: "Riverside Drive, NY 10024",
    price: 0,
    isSaved: false,
  },
  {
    id: "8",
    title: "Neo-Soul Sunday",
    description: "An afternoon of neo-soul music from the city's most exciting rising artists.",
    category: "Music",
    date: "2024-10-13",
    startTime: "15:00",
    endTime: "19:00",
    venue: "Rooftop Lounge",
    address: "55 Soul Street, Harlem, NY 10026",
    price: 35,
    isSaved: false,
  },
  {
    id: "9",
    title: "Techno Warehouse",
    description: "A raw industrial setting meets cutting-edge electronic music. One night only.",
    category: "Music",
    date: "2024-10-20",
    startTime: "23:00",
    endTime: "06:00",
    venue: "The Warehouse",
    address: "9 Industrial Ave, Brooklyn, NY 11201",
    price: 40,
    isSaved: false,
  },
];

export const EVENTS_BY_DATE: Record<string, string[]> = {
  "2024-10-02": ["4"],
  "2024-10-05": ["1", "2", "3", "5"],
  "2024-10-08": ["6"],
  "2024-10-13": ["8"],
  "2024-10-15": ["7"],
  "2024-10-20": ["9"],
};
